version: 1.0-{build}-{branch}
image: Visual Studio 2017
init:
    - choco install wget

environment:
  global:
    PYTHON: C:\Miniconda36-x64
    PYTHON_ARCH: "64"
    REPO_DIR: "smcp"
    PACKAGE_NAME: "smcp"
    BUILD_COMMIT: "v0.4.6"
    BUILD_DEPENDS: ""
    TEST_DEPENDS: ""

  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "3.5"
    - PYTHON_VERSION: "3.4"
      COMPILER: mingwpy
    - PYTHON_VERSION: "2.7"
      COMPILER: mingwpy

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: true

install:
    - if [%PYTHON_ARCH%]==[64] (
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      ) else (
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
      )

    # Set up miniconda build environment
    - SET "PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%ProgramFiles%\7-Zip;%PATH%"
    - conda info
    - conda create --yes -n build_env python=%PYTHON_VERSION% %BUILD_DEPENDS%
    - activate build_env
    - if [%COMPILER%]==[mingwpy] ( pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy )

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

    # Clone CHOMPACK
    - git clone https://github.com/cvxopt/smcp.git

build_script:
    # Build wheel
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - if [%COMPILER%]==[mingwpy] ( python setup.py build --compiler=mingw32 )
      else ( python setup.py build --compiler=msvc )
    - python setup.py bdist_wheel
    - ls dist/*

test_script:
    # Create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% %TEST_DEPENDS%
    - activate test_env

    # Install from wheel
    - pip install chompack
    - pip install --no-index --find-links dist/ %PACKAGE_NAME%

    # Run tests
    - python --version
    - python -c "from smcp import *"
    - python example.py

artifacts:
    - path: smcp/dist/*.whl

